/**
 * Traducción ES de tags de MangaDex (MangaDex los sirve solo en EN/JA).
 * Basado en catálogo público de tags. Fallback a nombre EN si no hay match.
 */
export const TAG_ES: Record<string, string> = {
  Action: 'Acción',
  Adventure: 'Aventura',
  Comedy: 'Comedia',
  Drama: 'Drama',
  Fantasy: 'Fantasía',
  Horror: 'Terror',
  Mystery: 'Misterio',
  Romance: 'Romance',
  'Sci-Fi': 'Ciencia ficción',
  'Slice of Life': 'Vida cotidiana',
  Sports: 'Deportes',
  Supernatural: 'Sobrenatural',
  Thriller: 'Suspenso',
  Tragedy: 'Tragedia',
  Isekai: 'Isekai',
  Magic: 'Magia',
  'Martial Arts': 'Artes marciales',
  Ninja: 'Ninja',
  Samurai: 'Samurái',
  Monsters: 'Monstruos',
  Demons: 'Demonios',
  Zombies: 'Zombis',
  Vampires: 'Vampiros',
  Ghosts: 'Fantasmas',
  Mecha: 'Mecha',
  Military: 'Militar',
  Police: 'Policíaco',
  Psychological: 'Psicológico',
  Historical: 'Histórico',
  Medical: 'Médico',
  Cooking: 'Cocina',
  Music: 'Música',
  'Video Games': 'Videojuegos',
  School: 'Escolar',
  'School Life': 'Vida escolar',
  Survival: 'Supervivencia',
  'Post-Apocalyptic': 'Post-apocalíptico',
  Gore: 'Gore',
  Crime: 'Crimen',
  Mafia: 'Mafia',
  Gyaru: 'Gyaru',
  Harem: 'Harem',
  'Reverse Harem': 'Harem inverso',
  'Girls\' Love': 'Chicas',
  'Boys\' Love': 'Chicos',
  Shota: 'Shota',
  Loli: 'Loli',
  Adaptation: 'Adaptación',
  Anthology: 'Antología',
  'Award Winning': 'Premiado',
  'Long Strip': 'Webtoon',
  'Full Color': 'Color',
  'Self-Published': 'Autopublicado',
  'Fan Colored': 'Coloreado por fans',
  Oneshot: 'Oneshot',
  'Web Comic': 'Web cómic',
  Doujinshi: 'Doujinshi',
  'Official Colored': 'Color oficial',
  'User Created': 'Creado por usuario',
  Aliens: 'Alienígenas',
  Animals: 'Animales',
  Anthropomorphic: 'Antropomórfico',
  Ninjas: 'Ninjas',
  Office: 'Oficina',
  'Reincarnation': 'Reencarnación',
  'Time Travel': 'Viajes en el tiempo',
  'Traditional Games': 'Juegos tradicionales',
  Villainess: 'Villana',
  Wuxia: 'Wuxia',
  Xianxia: 'Xianxia',
  Xuanhuan: 'Xuanhuan',
  'Magical Girls': 'Chicas mágicas',
  'Super Power': 'Superpoderes',
  Superhero: 'Superhéroe',
  Virtual: 'Virtual',
  'Video Game': 'Videojuego',
  'Crossdressing': 'Crossdressing',
  Genderswap: 'Cambio de género',
  Delinquents: 'Delincuentes',
};

export function translateTag(name: string): string {
  return TAG_ES[name] ?? name;
}
